
package com.webserviceoliday.holidayservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Web service that calculates holiday dates. (Version 2.0.1)
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolidayService2", targetNamespace = "http://www.holidaywebservice.com/HolidayService_v2/", wsdlLocation = "http://www.holidaywebservice.com/HolidayService_v2/HolidayService2.asmx?WSDL")
public class HolidayService2
    extends Service
{

    private final static URL HOLIDAYSERVICE2_WSDL_LOCATION;
    private final static WebServiceException HOLIDAYSERVICE2_EXCEPTION;
    private final static QName HOLIDAYSERVICE2_QNAME = new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.holidaywebservice.com/HolidayService_v2/HolidayService2.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLIDAYSERVICE2_WSDL_LOCATION = url;
        HOLIDAYSERVICE2_EXCEPTION = e;
    }

    public HolidayService2() {
        super(__getWsdlLocation(), HOLIDAYSERVICE2_QNAME);
    }

    public HolidayService2(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLIDAYSERVICE2_QNAME, features);
    }

    public HolidayService2(URL wsdlLocation) {
        super(wsdlLocation, HOLIDAYSERVICE2_QNAME);
    }

    public HolidayService2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLIDAYSERVICE2_QNAME, features);
    }

    public HolidayService2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolidayService2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolidayService2Soap
     */
    @WebEndpoint(name = "HolidayService2Soap")
    public HolidayService2Soap getHolidayService2Soap() {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2Soap"), HolidayService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidayService2Soap
     */
    @WebEndpoint(name = "HolidayService2Soap")
    public HolidayService2Soap getHolidayService2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2Soap"), HolidayService2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns HolidayService2Soap
     */
    @WebEndpoint(name = "HolidayService2Soap12")
    public HolidayService2Soap getHolidayService2Soap12() {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2Soap12"), HolidayService2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidayService2Soap
     */
    @WebEndpoint(name = "HolidayService2Soap12")
    public HolidayService2Soap getHolidayService2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2Soap12"), HolidayService2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns HolidayService2HttpGet
     */
    @WebEndpoint(name = "HolidayService2HttpGet")
    public HolidayService2HttpGet getHolidayService2HttpGet() {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2HttpGet"), HolidayService2HttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidayService2HttpGet
     */
    @WebEndpoint(name = "HolidayService2HttpGet")
    public HolidayService2HttpGet getHolidayService2HttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2HttpGet"), HolidayService2HttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns HolidayService2HttpPost
     */
    @WebEndpoint(name = "HolidayService2HttpPost")
    public HolidayService2HttpPost getHolidayService2HttpPost() {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2HttpPost"), HolidayService2HttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidayService2HttpPost
     */
    @WebEndpoint(name = "HolidayService2HttpPost")
    public HolidayService2HttpPost getHolidayService2HttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.holidaywebservice.com/HolidayService_v2/", "HolidayService2HttpPost"), HolidayService2HttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLIDAYSERVICE2_EXCEPTION!= null) {
            throw HOLIDAYSERVICE2_EXCEPTION;
        }
        return HOLIDAYSERVICE2_WSDL_LOCATION;
    }

}
